name: iOS App Release Build

on:
  push:
    tags:
      - 'ios/v[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS app
        working-directory: apps/mobile
        run: eas build --platform ios --local --non-interactive --output ${{ github.workspace }}/app-release.ipa
        env:
          EAS_SKIP_AUTO_FINGERPRINT: "1"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: karakeep-ios
          path: ${{ github.workspace }}/app-release.ipa
